### Random Forest

In [2]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
from sklearn.preprocessing import StandardScaler
from utils.preprocess import create_features
from utils.data_split import split_data
from utils.metrics import evaluate, realized_cost, expected_calibration_error, bootstrap_ci
from utils.thresholds import thr_for_precision, thr_min_cost, sweep_thresholds
from imblearn.over_sampling import SMOTE
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('../../../data/creditcard.csv')
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [4]:
df = create_features(df)
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V25,V26,V27,V28,Amount,Class,_log_amount,Hour_from_start_mod24,is_night_proxy,is_business_hours_proxy
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,0.128539,-0.189115,0.133558,-0.021053,149.62,0,5.014760,0,1,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,0.167170,0.125895,-0.008983,0.014724,2.69,0,1.305626,0,1,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0,5.939276,0,1,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,0.647376,-0.221929,0.062723,0.061458,123.50,0,4.824306,0,1,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.206010,0.502292,0.219422,0.215153,69.99,0,4.262539,0,1,0

In [5]:
scaler = StandardScaler()
df['Amount'] = scaler.fit_transform(df[['Amount']])
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V25,V26,V27,V28,Amount,Class,_log_amount,Hour_from_start_mod24,is_night_proxy,is_business_hours_proxy
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,0.128539,-0.189115,0.133558,-0.021053,0.244200,0,5.014760,0,1,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,0.167170,0.125895,-0.008983,0.014724,-0.342584,0,1.305626,0,1,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,-0.327642,-0.139097,-0.055353,-0.059752,1.158900,0,5.939276,0,1,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,0.647376,-0.221929,0.062723,0.061458,0.139886,0,4.824306,0,1,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.206010,0.502292,0.219422,0.215153,-0.073813,0,4.262539,0,1,0

In [6]:
features = df.corr()['Class'].drop('Class').abs()
features = features.drop('Time').sort_values(ascending=False).index.tolist()
print(features)

['V17', 'V14', 'V12', 'V10', 'V16', 'V3', 'V7', 'V11', 'V4', 'V18', 'V1', 'V9', 'V5', 'V2', 'V6', 'V19', 'V8', 'V21', 'V27', 'V20', 'Hour_from_start_mod24', 'is_night_proxy', 'V28', '_log_amount', 'V24', 'V23', 'Amount', 'is_business_hours_proxy', 'V22', 'V26', 'V13', 'V15', 'V25']

In [7]:
X = df[features]
y = df['Class']

print(X.shape, y.shape)

(283726, 33) (283726,)

In [33]:
X_train, y_train, X_val, y_val, X_test, y_test = split_data(df, features, 'Class')

X_train:              V17       V14       V12       V10       V16        V3        V7  \
0       0.207971 -0.311169 -0.617801  0.090794 -0.470401  2.536347  0.239599
1      -0.114805 -0.143772  1.065235 -0.166974  0.463917  0.166480 -0.078803
2       1.109969 -0.165946  0.066084  0.207643 -2.890083  1.773209  0.791461
3      -0.684093 -0.287924  0.178228 -0.054952 -1.059647  1.792993  0.237609
4      -0.237033 -1.119670  0.538196  0.753074 -0.451449  1.548718  0.592941
...          ...       ...       ...       ...       ...       ...       ...
181579 -0.361219  0.616211  0.247209 -0.087831 -0.418021 -1.813615  0.711378
181580  0.042739 -1.152530  0.694689  0.625693 -1.325917  0.701881 -2.048749
181581 -0.372886 -1.188370 -0.750049  3.213693 -0.135354  1.561304  0.357187
181582 -0.047588  0.308283 -0.112697  0.725841 -0.629282  0.363199 -0.247814
181583 -0.767461 -0.021656  0.866061  0.180293  0.508146 -0.390832 -0.736245

             V11        V4       V18  ...  _log_amount       V24       V23  \
0      -0.551600  1.378155  0.025791  ...     5.014760  0.066928 -0.110474
1       1.612727  0.448154 -0.183361  ...     1.305626 -0.339846  0.101288
2       0.624501  0.379780 -0.121359  ...     5.939276 -0.689281  0.909412
3      -0.226487 -0.863291  1.965775  ...     4.824306 -1.175575 -0.190321
4      -0.822843  0.403034 -0.038195  ...     4.262539  0.141267 -0.137458
...          ...       ...       ...  ...          ...       ...       ...
181579 -0.894587  0.521401 -0.288679  ...     5.238408 -0.079110 -0.143750
181580 -0.700094  0.020085  1.939160  ...     4.330733 -0.301705  0.158403
181581 -0.868346  4.640512  0.301390  ...     2.304583  0.066925  0.412942
181582  0.017863  0.656021  0.468382  ...     2.564180 -1.427334  0.396445
181583  0.439939  0.311711  0.531906  ...     2.639771 -0.333598  0.085059

          Amount  is_business_hours_proxy       V22       V26       V13  \
0       0.244200                        0  0.277838 -0.189115 -0.991390
1      -0.342584                        0 -0.638672  0.125895  0.489095
2       1.158900                        0  0.771679 -0.139097  0.717293
3       0.139886                        0  0.005274 -0.221929  0.507757
4      -0.073813                        0  0.798278  0.502292  1.345852
...          ...                      ...       ...       ...       ...
181579  0.394959                        1  0.315181 -0.212772 -0.129505
181580 -0.053805                        1  0.165367  0.736998 -0.515887
181581 -0.317304                        1  1.156130  0.376197  0.469171
181582 -0.305443                        1 -0.237641  0.792794 -0.358377
181583 -0.301370                        1  0.857953  0.619494 -0.054356

             V15       V25
0       1.468177  0.128539
1       0.635558  0.167170
2       2.345865 -0.327642
3      -0.631418  0.647376
4       0.175121 -0.206010
...          ...       ...
181579  0.355176  0.245283
181580 -2.245623 -0.539162
181581  0.788992 -0.547366
181582  1.054874  0.344498
181583 -0.301399 -0.230351

[181584 rows x 33 columns] y_train: 0         0
1         0
2         0
3         0
4         0
         ..
181579    0
181580    0
181581    0
181582    0
181583    0
Name: Class, Length: 181584, dtype: int32
X_val:              V17       V14       V12       V10       V16        V3        V7  \
181584 -0.573562  0.641407  0.513544  0.262347  0.193159 -1.231352 -0.006487
181585 -0.218648  0.483957  0.422251  0.237550 -0.668806 -1.660965  0.736634
181586 -0.641125  0.837662  0.358611 -0.502448 -0.495112 -0.554517  1.494051
181587 -0.148545  0.470170  0.087651 -1.838525  0.481208  0.588308  0.217347
181588  0.056109 -1.532092  1.334165 -0.383746 -0.200667  0.875649 -1.463463
...          ...       ...       ...       ...       ...       ...       ...
226975  0.314462 -0.158043  0.767475  0.646272 -2.432985 -0.972739 -0.200564
226976 -0.186837  0.364564 -0.149205  1.873887 -0.134914  0.622397  0.498785
226977 -0.914250 -0.426757  1.200483 -0.208792  0.328839 -0.528350 -0.357983
226978 -0.251720  0.891151  0.417318  0.890423  0.299821 -0.966024  0.099967
226979  0.013343 -0.856012 -0.531412 -0.270898  1.219476  1.523218  1.334304

             V11        V4       V18  ...  _log_amount       V24       V23  \
181584  0.490205  0.207806 -0.217382  ...     0.688135 -0.491970  0.297217
181585 -1.033419  1.419606 -0.573542  ...     4.025352 -0.009302 -0.060133
181586  0.317093 -0.508274  0.630601  ...     4.541058 -0.366204  0.037841
181587 -1.498044 -2.190599 -0.671989  ...     4.598649 -0.112398 -0.016818
181588 -1.579729  0.839468 -0.229082  ...     3.499533  0.169489  0.146026
...          ...       ...       ...  ...          ...       ...       ...
226975 -0.829451  0.010592  0.761765  ...     2.525729  0.496001  0.075393
226976  0.093678  4.129344  0.865541  ...     2.450143  0.271546 -0.257843
226977 -1.187789  0.266611 -0.164165  ...     0.113329 -0.713557  0.265277
226978  0.420680 -0.835373 -0.103937  ...     2.955431  0.010709  0.260094
226979 -0.644749 -1.598932 -0.826311  ...     5.826000  0.063405 -0.211676

          Amount  is_business_hours_proxy       V22       V26       V13  \
181584 -0.349373                        1 -0.713347  0.211590 -0.898704
181585 -0.133677                        1  0.335834 -0.496590  0.016103
181586  0.017242                        1  0.996400 -0.647207 -0.627317
181587  0.039446                        1 -1.457343  0.170764 -1.082522
181588 -0.225131                        1  0.852154  0.731150  0.950478
...          ...                      ...       ...       ...       ...
226975 -0.307400                        1  0.373515 -0.085769  0.832736
226976 -0.311034                        1  1.379516  0.595315  0.357304
226977 -0.352848                        1 -0.357425 -0.582657  1.952948
226978 -0.280603                        1 -0.696985  0.149179 -1.472768
226979  0.996519                        1  1.210480  0.132667  1.493834

             V15       V25
181584 -0.480432 -0.321955
181585 -0.583848  0.472975
181586 -0.526887 -0.711238
181587 -0.642059  0.468352
181588 -1.613046 -0.367980
...          ...       ...
226975 -0.805512  0.245824
226976 -0.254897 -0.455101
226977  0.515379 -0.267093
226978 -0.937780 -0.270808
226979  0.531138  0.635125

[45396 rows x 33 columns] y_val: 181584    0
181585    0
181586    0
181587    0
181588    0
         ..
226975    0
226976    0
226977    0
226978    0
226979    0
Name: Class, Length: 45396, dtype: int32
X_test:              V17       V14       V12       V10       V16        V3        V7  \
226980  0.384325 -1.104946  0.135209 -0.855009  0.260986 -0.407432  0.987183
226981  0.058459 -0.002649  0.525138 -0.304027 -0.609545 -1.131660 -0.057589
226982  0.300623 -0.782531  1.317389 -0.239977  0.366544 -1.592491  0.122240
226983 -0.436657  0.893645 -0.031848  0.145524 -0.740981 -2.593920  0.900367
226984  1.498607 -4.898780 -1.188055  6.089008 -0.187016 -0.921581  1.887713
...          ...       ...       ...       ...       ...       ...       ...
283721  1.991691  4.626942  2.711941  4.356170  1.107641 -9.834783 -4.918215
283722 -0.025693 -0.675143  0.915802 -0.975926 -0.711757  2.035030  0.024330
283723  0.509928  0.449624 -0.962886 -0.399126 -0.608577  0.702510 -0.686180
283724  0.313502 -0.510602  0.063119 -0.484782  0.140716 -3.249640 -0.296827
283725 -0.660377 -0.084316 -0.031513 -0.915427 -0.302620  0.703337  1.577006

             V11        V4       V18  ...  _log_amount       V24       V23  \
226980 -0.591849 -0.562355 -0.350801  ...     1.026042  0.512207  0.089250
226981 -0.966627 -0.376639 -0.636697  ...     0.693147  0.153868  0.076309
226982  1.470214  0.328102 -0.052646  ...     0.688135  0.630989  0.347722
226983 -0.159291 -2.275246 -0.524271  ...     1.547563  0.746750 -0.179844
226984  0.707218  4.012684  0.379803  ...     1.313724 -0.356949  0.053142
...          ...       ...       ...  ...          ...       ...       ...
283721 -1.593105 -2.066656  0.510632  ...     0.570980 -0.509348  1.014480
283722 -0.150189 -0.738589 -1.221179  ...     3.249987 -1.016226  0.012463
283723 -1.933849  0.689799  1.113981  ...     2.397895  0.123205 -0.163298
283724  0.411614 -0.557828  0.395652  ...     4.232366  0.640134 -0.037501
283725 -1.040458 -0.506271  0.167430  ...     5.384495  0.008797  0.376777

          Amount  is_business_hours_proxy       V22       V26       V13  \
226980 -0.346178                        1 -0.779618  0.117893  0.466588
226981 -0.349333                        1  0.467391  0.999199 -0.098905
226982 -0.349373                        1 -0.713194  0.145796  0.702631
226983 -0.338550                        1  0.769298  0.092126 -0.440343
226984 -0.342464                        1 -0.972359 -0.149689  0.482440
...          ...                      ...       ...       ...       ...
283721 -0.350252                        0  0.111864  0.250034 -0.689256
283722 -0.254325                        0  0.924384 -0.395255  1.214756
283723 -0.313391                        0  0.800049  0.546668 -1.042082
283724 -0.082239                        0  0.578229 -0.087371 -0.183699
283725  0.513290                        0  0.643078 -0.818267 -0.188093

             V15       V25
226980 -0.239878 -0.416654
226981 -0.374051  0.025768
226982 -0.544201 -0.301153
226983  0.263460 -0.174443
226984  0.934694 -0.284736
...          ...       ...
283721 -0.924459  1.436807
283722  1.164931 -0.606624
283723  1.962563 -0.569159
283724  1.329284  0.265745
283725  0.041333 -0.473649

[56746 rows x 33 columns] y_test: 226980    0
226981    0
226982    0
226983    0
226984    0
         ..
283721    0
283722    0
283723    0
283724    0
283725    0
Name: Class, Length: 56746, dtype: int32
Fraud rate in train: 0.001910961318177813
Fraud rate in test: 0.0013040566735981391

In [9]:
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

In [10]:
X_train_resampled.shape, y_train_resampled.shape

((362474, 33), (362474,))

In [11]:
rf_model = RandomForestClassifier(
    n_estimators=300, 
    class_weight='balanced',
    max_depth=10,
    min_samples_split=5,
    random_state=42,
    n_jobs=-1)

In [12]:
rf_model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', max_depth=10,
                       min_samples_split=5, n_estimators=300, n_jobs=-1,
                       random_state=42)

In [32]:
thr, cost = thr_min_cost(y_test, y_score_rf)

print(f"Best threshold: {thr}")
print(f"Min cost: {cost}")

Best threshold: 0.11900000000000001
Min cost: 2910.0